---
version: '3.8'

services:
  db:
    image: mysql:8.2-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
        - db:/var/lib/mysql
    ports:
        - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  db:
